kind: Service
apiVersion: v1
metadata:
  name: demo-svc
  labels:
    name: demo-svc
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
  selector:
    app: demo
